remote_theme: pages-themes/midnight@v0.2.0
title: "Xingqi-Xia's Homepage"
# tagline: [A very short description of your site's purpose, used as subtitle]
# description: "I'm ... not available now"
github_username: Xingqi-Xia
plugins:
- jekyll-remote-theme
